### ISSUE TITLE
[system] 限流框架 limit

### ISSUE THREAD

**Issue by Alice52** [Alice52/system-design#20]
## overview 

1. 需求分析
   - 功能需求: 
     1. 不同应用有不同的限流值
     2. 可配置粒度到api级别
     3. 限流器: 内存, 分布式内存
   - 扩展: 非嵌入式的配置限流规则(支持多种配置文件) | 多种数据源(zk, etcd, nacos等)
   - *扩展: 可自定义限流器*
   - 易用: aop 切面内调用限流接口, 并将其封装在xx-starter中作为默认策略
   - 性能: 超低延迟(少业务, redis超时设置)
   - 高并发: 超高并发(下发逻辑到处理单元)
   - 容错性: 限流服务党纪, 不影响已有服务

2. 设计: oop 主要产出是类对象及关系
   - 类: 限流规则-规则解析(fatory)
      ```yaml
      configs: 
        - appId: app-1
          limits:
            - api: /v1/user
              limit: 100
              unit：60
            - api: /v2/user
              limit: 100
              unit：60
      ```
   - 类: 限流算法(4种)
   - 类: 限流模式(单机 | 分布式{redis超时})
   - 类: 限流类型(Http/Rpc)
   - 组装: 集成使用(xx-starter&default-impl)

### v1

1. 限流类型: 只支持 Http 限流, 暂时不支持RPC限流
2. 限流规则: 只支持本地文件的Yaml格式配置, 之后支持多种配置文件, 和服务配置通知修改
3. 限流算法: 只支持固定时间窗口限流
4. 限流模式： all

## detail

1. raw struct
   ```java
   com.xzg.ratelimiter
      - RateLimiter: 服务聚合类, 限流核心
   com.xzg.ratelimiter.rule
      - RuleConfig: yaml 解析结果 | <app, ApiLimits>
      - ApiLimit: store uri, threshold
      - RateLimitRule
   com.xzg.ratelimiter.alg
      - RateLimitAlg: 限流算法
   ```   
2. refactor

   ```java
   com.xzg.ratelimiter
      - AbstractRateLimiter
      - LocalRateLimiter
   com.xzg.ratelimiter.rule
      - ApiLimit(不变)
      - RuleConfig(不变)
      - RateLimitRule(抽象接口)
      - TrieRateLimitRule(实现类, 就是重构前的 RateLimitRule）
   com.xzg.ratelimiter.rule.parser
      - RuleConfigParser(抽象接口)
      - YamlRuleConfigParser(Yaml格式配置文件解析类)
      - JsonRuleConfigParser(Json格式配置文件解析类)
   com.xzg.ratelimiter.rule.datasource
      - RuleConfigSource(抽象接口)
      - FileRuleConfigSource(基于本地文件的配置类)
   com.xzg.ratelimiter.alg
      - RateLimitAlg(抽象接口)
   ```

## optimize

1. 统一集中管理配置, 通过 rpc 调用平台判断是否限流
    - 方便线上修改管理
    - 但是统一入口, 处理的流量比较大, 高可用有成本

5. 将限流处理成组件, 业务执行下发到业务实例
   
   - 不方便修改: 可以一服务配置通知方式修改
   - 处理流量比较大, 可以处理超高并发

## reference

1. xxx
